#!/bin/bash

basedir=`dirname $0`
python $basedir/source/gui/guiclient.py - $1 $2 $3 $4 $5 $6 $7 $8 $9

#To run as interactive ipython shell
#ipython -gthread $basedir/source/gui/guiclient.py - $1 $2 $3 $4 $5 $6 $7 $8 $9
